name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Bun.js
        uses: antongolub/action-setup-bun@v1
        with:
          bun-version: 0.6.12
          bun-repo: "Jarred-Sumner/bun-releases-for-updater"
          platform: "linux"
      - run: bun install
      - run: bun run build
      - run: bun run test
