name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  setup-bun:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup-bun
        name: Setup Bun
        uses: ./
        with:
          bun-version: 0.6.12
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run build
      - name: Test
        run: bun run test
