name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Bunjs
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "0.6.12"
      - name: Install dependencies
        run: bun install
      - run: bun run build
      - run: bun run test
